### ISSUE TITLE
Data to test locate package

### ISSUE THREAD

**Issue by gegen07** [gegen07/spopt#2]
@jGaboardi, @ljwolf, @qszhao. 
I was digging into the [libpysal.examples](https://github.com/pysal/libpysal/blob/master/libpysal/examples) repository to search for a dataset to use to test the facloc models. I found the [streets.shp](https://github.com/pysal/libpysal/blob/master/libpysal/examples/geodanet/streets.shp) and I would like to know if it has some spatial relation with [street_net_pts.shp](https://github.com/pysal/libpysal/blob/master/libpysal/examples/street_net_pts/street_net_pts.shp). They have the same prefix so arose me this question.

**Comment by jGaboardi** [comment]
In several of the `spaghetti` Tutorials I used two empirical datasets available through [`libpysal.examples`](https://pysal.org/libpysal/api.html#examples). In the [Quickstart](https://pysal.org/spaghetti/notebooks/quickstart.html) tutorial I use [school](https://pysal.org/spaghetti/notebooks/quickstart.html#Schools-without-attributes) and [crime](https://pysal.org/spaghetti/notebooks/quickstart.html#Crimes-with-attributes) locations. There are 7 points in the schools data and there are nearly 300 points in the crimes data. I used a subset of 14 crimes in the [TSP](https://pysal.org/spaghetti/notebooks/tsp.html#Detective-Königsberg’s-cases). You could do something like this if you wanted to, or create even more basic synthetic data.

**Comment by gegen07** [comment]
Hm... Great! I was thinking, and this school data can be used in the documentation, so, the synthetic data may be created to test. What do you think?

**Comment by jGaboardi** [comment]
First, I'll give my broad answer of "Having both synthetic and empirical data are important for both testing and demonstration purposes." LOL. Second, I'll say that getting things working with synthetic data and being able to verify solutions is top priority. Let's focus on that first, then we can look at incorporating the empirical data. This will be the 'getting things going phase.' Once the code base is functional and in good order, we can focus back on docstring examples and tutorials. How does that sound?

**Comment by gegen07** [comment]
Totally agreed. All questions about this topic are cleared, I'll close this issue for now. Thanks!!
