### ISSUE TITLE
Where to add results to the models

### ISSUE THREAD

**Issue by gegen07** [gegen07/spopt#4]
I'm trying to think of a way to add the results to each model. I've already coded a simple way but I think it's not good enough because I'm only considering the coverage model. Here it's the [class](https://github.com/gegen07/spopt/blob/gsoc21-facloc/spopt/locate/coverage.py#L12) I'm talking about.

I'm thinking that would be good to remove the [``client_facility_dict``](https://github.com/gegen07/spopt/blob/gsoc21-facloc/spopt/locate/coverage.py#L21) and [``__init__``](https://github.com/gegen07/spopt/blob/gsoc21-facloc/spopt/locate/coverage.py#L13) methods from Coverage class, but I don't know where it's the best place to put it. [LocateSolver](https://github.com/gegen07/spopt/blob/gsoc21-facloc/spopt/locate/base.py#L10) is a good place since all models inherit LocateSolver?

@jGaboardi, @ljwolf, @qszhao

**Comment by jGaboardi** [comment]
> I'm thinking that would be good to remove the client_facility_dict and __init__ methods from Coverage class, but I don't know where it's the best place to put it. LocateSolver is a good place since all models inherit LocateSolver?

This sounds reasonable to me since all facility location models should have an attribute for client-facility lookup. Also, we will also want an attribute that records the objective value of the model.

**Comment by gegen07** [comment]
Great! One thing to add, how the structure of the facility client lookup result should be? For now, it's on dictionaries. It's a good manner to compile these kinds of results?

**Comment by gegen07** [comment]
We've decided to use an array to output the results, as this makes it easier and faster than dict based to manage. The outputs are placed inside Mixins which are related to each model. The [`CoveragePercentageMixin`](https://github.com/gegen07/spopt/blob/gsoc21-facloc/spopt/locate/base.py#L54) is related to MCLP, so only MCLP class inherits the Mixin.
